### PR TITLE
Support EdDSA for JWT

### PR DESCRIPTION
**Pull request by crossle**
We use EdDSA for our SDK, it's smaller and efficient.

### CODE REVIEW

**Comment by jonasroussel** [comment]
Thanks ! A really good PR.

I will publish a new version with this new feature soon.

**Comment by crossle** [comment]
When publish stable null safety version?

**Comment by jonasroussel** [comment]
When `pointycastle` package will be nullsafe on stable

**Comment by jonasroussel** [comment]
`pointycastle` (nullsafety) is now stable. I published the v2.0.0 today !

**Comment by crossle** [comment]
Coooool

**Pull request merged**
